---

name: Complete Devops Project

on:
  push:
    branches:
    - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Short SHA
      run: |
        echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t codecarl84/terraform-lab1:${{ env.SHORT_SHA }} .

    - name: Login to Dockerhub
      run: echo "${{secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Image to Dockerhub
      run: docker push codecarl84/terraform-lab1:${{ env.SHORT_SHA }}
